// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int N =  Integer.parseInt(args[0]);
		int sumB = 0;
		int sumL = 0;

		for (int i = 1; i <= N; i++){
			double a = (Math.random());
			//System.out.println(a); //debuger
			if (a>0.5) sumB++ ;
			else sumL++ ; 
		   }
		   
		   System.out.println("> 0.5: "+sumB+" times");
		   System.out.println("<= 0.5: "+sumL+" times");
	    //int a = (int) (N* Math.random()); //reminder for me
	}
}
